name: esPoint
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.25.4
  cloud_firestore: ^4.14.0

  # State Management
  provider: ^6.1.2

  # Utilities
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  flutter_local_notifications: ^17.0.0
  fluttertoast: ^8.2.4
  connectivity_plus: ^6.0.3

  # Charts & Export
  fl_chart: ^0.66.2
  pdf: ^3.10.8
  printing: ^5.12.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
